#!/bin/sh
#
# This file is protected by Copyright. Please refer to the COPYRIGHT file distributed with this 
# source distribution.
# 
# This file is part of REDHAWK Basic Components TuneFilterDecimate.
# 
# REDHAWK Basic Components TuneFilterDecimate is free software: you can redistribute it and/or modify it under the terms of 
# the GNU General Public License as published by the Free Software Foundation, either 
# version 3 of the License, or (at your option) any later version.
# 
# REDHAWK Basic Components TuneFilterDecimate is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; 
# without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR 
# PURPOSE.  See the GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License along with this 
# program.  If not, see http://www.gnu.org/licenses/.
#

rm -f config.cache

# Setup the libtool stuff
if [ -e /usr/local/share/aclocal/libtool.m4 ]; then
    /bin/cp /usr/local/share/aclocal/libtool.m4 aclocal.d/acinclude.m4
elif [ -e /usr/share/aclocal/libtool.m4 ]; then
    /bin/cp /usr/share/aclocal/libtool.m4 acinclude.m4
fi
libtoolize --force --automake

# Search in expected locations for the OSSIE acincludes
BOOST_AC_INCLUDE=${PWD}/local_ac_includes

aclocal -I ${BOOST_AC_INCLUDE=}

autoconf
automake --foreign --add-missing
